# -*- coding: utf-8 -*-
"""Copy of Mutual_Fund.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TofJa38P-3lCrwQ9DGDhceOtH9OfBMni
"""

import subprocess
import sys

# Function to install packages
def install_packages():
    try:
        import streamlit as st
        import requests
        import pandas as pd
        import matplotlib.pyplot as plt
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit", "requests", "pandas", "matplotlib"])
        import streamlit as st
        import requests
        import pandas as pd
        import matplotlib.pyplot as plt

# Call the function to install packages
install_packages()

# Streamlit setup
import streamlit as st
import requests
import pandas as pd
import matplotlib.pyplot as plt

st.title("Mutual Fund NAV Trend Viewer")

# Input for Mutual Fund Code
fund_code = st.text_input("Enter Mutual Fund Code", value="150738")

# API URL construction
api_url = f"https://api.mfapi.in/mf/{fund_code}"

# Fetching data from the API
response = requests.get(api_url)
data = response.json()

if 'meta' in data and 'scheme_name' in data:
    # Extracting scheme name and NAV data
    scheme_name = data['meta']['scheme_name']
    nav_data = data['data']

    # Creating a DataFrame from the NAV data
    df = pd.DataFrame(nav_data)

    # Converting date and nav values to appropriate types
    df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
    df['nav'] = df['nav'].astype(float)

    # Sorting the DataFrame by date
    df = df.sort_values(by='date')

    # Date range slider
    start_date = df['date'].min()
    end_date = df['date'].max()
    date_range = st.slider("Select Date Range", min_value=start_date, max_value=end_date, value=(start_date, end_date))

    # Filtering data based on selected date range
    filtered_df = df[(df['date'] >= date_range[0]) & (df['date'] <= date_range[1])]

    # Plotting the NAV trend over time
    st.write(f"NAV Trend for {scheme_name}")
    plt.figure(figsize=(10, 6))
    plt.plot(filtered_df['date'], filtered_df['nav'], marker='o', linestyle='-', color='b')
    plt.title(f'NAV Trend for {scheme_name} ({date_range[0].strftime("%Y-%m-%d")} to {date_range[1].strftime("%Y-%m-%d")})')
    plt.xlabel('Date')
    plt.ylabel('NAV')
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()

    # Displaying the plot in Streamlit
    st.pyplot(plt)

else:
    st.error("Invalid Mutual Fund Code or data not available. Please try again.")